// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC38bvV8la-OOa3Lar7rSTahit0dBmQy4U',
    appId: '1:298480493888:web:aafa8fcb7e2065a4ee46a5',
    messagingSenderId: '298480493888',
    projectId: 'quizzo-f4626',
    authDomain: 'quizzo-f4626.firebaseapp.com',
    storageBucket: 'quizzo-f4626.appspot.com',
    measurementId: 'G-XY20V39PBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvNkk4kl7JOfJuirS868snrO8D_0rBeeI',
    appId: '1:298480493888:android:d9e6e02353b04401ee46a5',
    messagingSenderId: '298480493888',
    projectId: 'quizzo-f4626',
    storageBucket: 'quizzo-f4626.appspot.com',
  );
}
